### ISSUE TITLE
editing DV1/userStory.txt

### ISSUE THREAD

**Issue by Alireza89** [Alireza89/COEN-6311-Project#1]
according to https://www.visual-paradigm.com/guide/agile-software-development/what-is-user-story/,
we should follow this pattern for the user story:
As a role, I want action, (so that benefit)

examples:
As a [customer], I want [shopping cart feature] so that [I can easily purchase items online].
As an [manager], I want to [generate a report] so that [I can understand which departments need more resources].
As a [customer], I want to [receive an SMS when the item is arrived] so that [I can go pick it up right away]

note:
Role represents the person, system, subsystem or any entity else who will interact with the system to be implemented to achieve a goal. He or she will gain values by interacting with the system.
Action represents a user's expectation that can be accomplished through interacting with the system.
Benefits represents the value behind the interaction with the system.
as a owner of restuarant i want to encourage costumer to use vegetable food to decrease co2
as a resturant manager i want to access to my previous costumer  order

ADD TO THIS

**Comment by Alireza89** [comment]
this is not a proper user story:
as a resturant manager i want to access to my previous costumer order

**Comment by alipartovi1990** [comment]
as a owner of restuarant i want to encourage costumer to use veg food to reduce CO2

**Comment by alipartovi1990** [comment]
ok , so we can say
as a restuarant manager i want to tell my costumer how much the save co2 when they order a plant based food

**Comment by Alireza89** [comment]
I propose this:
As a owner of a vegan restaurant chain, I want to have an updating record of the green house gases which our customers save from emission to the atmosphere in order for advertisement purposes.

**Comment by alipartovi1990** [comment]
> I propose this:
> As a owner of a vegan restaurant chain, I want to have an updating record of the green house gases which our customers save from emission to the atmosphere in order for advertisement purposes.

great

**Comment by alipartovi1990** [comment]
as i sent use cases in Glip according to that file i  wrote user story for each use case . there are : 
Describe “user stories” for each use case :
As a server in restaurant I want to get costumer information (first name, last name, date of birth, email address)
As a server I want to get costumer order and book it in costumer history
As a server I want to print the amount of co2 saved by costumer in current order and give it to the costumer

As a manager i want to see what did each costumer order and the over all  gases was saved by that person
As a manager I want view the record of total order 
As a manger I want to write and modify restaurant menu 

As a owner I want to have an overview of order in each branch
As a owner I want to view the overall amount of gases which is saved by each restaurant.
