### ISSUE TITLE
editing DV1/TheProblemStatement.txt

### ISSUE THREAD

**Issue by Alireza89** [Alireza89/COEN-6311-Project#3]
What is our problem statement?

**Comment by Alireza89** [comment]
according to Wikipedia:
A PROBLEM STATEMENT is a concise description of an issue to be addressed or a condition to be improved upon. It identifies the gap between the current (problem) state and desired (goal) state of a process or product. Focusing on the facts, the problem statement should be designed to address the Five Ws. The first condition of solving a problem is understanding the problem, which can be done by way of a problem statement.[1]

**Comment by alipartovi1990** [comment]
according to http://www.ceptara.com/blog/how-to-write-problem-statement
the 5 'W's - Who, What, Where, When and Why - is a great tool that helps get pertinent information out for discussion
**Who - Who does the problem affect? Specific groups, organizations, customers, etc.

What - What are the boundaries of the problem, e.g. organizational, work flow, geographic, customer, segments, etc. - What is the issue? - What is the impact of the issue? - What impact is the issue causing? - What will happen when it is fixed? - What would happen if we didn’t solve the problem?

When - When does the issue occur? - When does it need to be fixed?

Where - Where is the issue occurring? Only in certain locations, processes, products, etc.

Why - Why is it important that we fix the problem? - What impact does it have on the business or customer? - What impact does it have on all stakeholders, e.g. employees, suppliers, customers, shareholders, etc. Each of the answers will help to zero in on the specific issue(s) and frame the Issue Statement. Your problem statement should be solveable. That is, it should take a reasonable amount of time to formulate, try and deploy a potential solution.**

**Comment by Alireza89** [comment]
my proposal is:
There is no tool to express the impact of consumption of the plant-based products quantitatively......

**Comment by Alireza89** [comment]
> according to http://www.ceptara.com/blog/how-to-write-problem-statement
> the 5 'W's - Who, What, Where, When and Why - is a great tool that helps get pertinent information out for discussion
> **Who - Who does the problem affect? Specific groups, organizations, customers, etc.
> 
> What - What are the boundaries of the problem, e.g. organizational, work flow, geographic, customer, segments, etc. - What is the issue? - What is the impact of the issue? - What impact is the issue causing? - What will happen when it is fixed? - What would happen if we didn’t solve the problem?
> 
> When - When does the issue occur? - When does it need to be fixed?
> 
> Where - Where is the issue occurring? Only in certain locations, processes, products, etc.
> 
> Why - Why is it important that we fix the problem? - What impact does it have on the business or customer? - What impact does it have on all stakeholders, e.g. employees, suppliers, customers, shareholders, etc. Each of the answers will help to zero in on the specific issue(s) and frame the Issue Statement. Your problem statement should be solveable. That is, it should take a reasonable amount of time to formulate, try and deploy a potential solution.**

do you have some examples of problem statement?

**Comment by alipartovi1990** [comment]
> > according to http://www.ceptara.com/blog/how-to-write-problem-statement
> > the 5 'W's - Who, What, Where, When and Why - is a great tool that helps get pertinent information out for discussion
> > **Who - Who does the problem affect? Specific groups, organizations, customers, etc.
> > What - What are the boundaries of the problem, e.g. organizational, work flow, geographic, customer, segments, etc. - What is the issue? - What is the impact of the issue? - What impact is the issue causing? - What will happen when it is fixed? - What would happen if we didn’t solve the problem?
> > When - When does the issue occur? - When does it need to be fixed?
> > Where - Where is the issue occurring? Only in certain locations, processes, products, etc.
> > Why - Why is it important that we fix the problem? - What impact does it have on the business or customer? - What impact does it have on all stakeholders, e.g. employees, suppliers, customers, shareholders, etc. Each of the answers will help to zero in on the specific issue(s) and frame the Issue Statement. Your problem statement should be solveable. That is, it should take a reasonable amount of time to formulate, try and deploy a potential solution.**
> 
> do you have some examples of problem statement?
no

**Comment by Alireza89** [comment]
is there any examples in the text book?

**Comment by alipartovi1990** [comment]
An example problem statement:
The staffing model in the Process Improvement Unit (PIU) has changed (we have more staff, and
some of the staff have different working patterns) we need to have a clear way of recording status
and stage of our business activities (projects, workshops and training) that will be used by all PIU
staff, so that we can work effectively and provide good service to our customers. A member of staff
is due to go on annual leave in two weeks time and we have no visibility or way of easily sharing
information about their work, this will make it hard for the rest of the team to cover the work during
staff absenc

**Comment by Alireza89** [comment]
> An example problem statement:
> The staffing model in the Process Improvement Unit (PIU) has changed (we have more staff, and
> some of the staff have different working patterns) we need to have a clear way of recording status
> and stage of our business activities (projects, workshops and training) that will be used by all PIU
> staff, so that we can work effectively and provide good service to our customers. A member of staff
> is due to go on annual leave in two weeks time and we have no visibility or way of easily sharing
> information about their work, this will make it hard for the rest of the team to cover the work during
> staff absenc

That's a very good example!
let's follow this pattern

**Comment by Alireza89** [comment]
Let's each of us write the problem statement from the perspective of the vegan restaurant chain owner and the compare

**Comment by alipartovi1990** [comment]
ok

**Comment by alipartovi1990** [comment]
> Let's each of us write the problem statement from the perspective of the vegan restaurant chain owner and the compare

ok lets do that

**Comment by Alireza89** [comment]
Many vegans have chosen to avoid animal-based products because of its harsh impact on the environment. While they are aware of the positive impacts of consuming plant-based foods, they might not know these impacts quantitatively.

**Comment by alipartovi1990** [comment]
According to american agricultural society in order to produce one kg meat, 34 kg co2 will be released in atmosphere .encouraging people to consume less meat is really important .one of the best way to inform people is telling them how much they will save if they do not use vegan,in fact many vegan do not know how much co2 will be saved when they are using plant based food.
designing a software to calculate the amount of co2 which is saved by vegan when they are ordering a plant based food instead of meat based food and reporting them the overall saved co2 in the year.
in addition they will notice that how much cholesterol and fat they will absorb if they use meat instead of vegan food.

**Comment by Alireza89** [comment]
Many vegans have chosen to avoid animal-based products because of its adverse environmental impacts. While they are aware of the positive impacts of consuming plant-based foods, they might not know these impacts quantitatively. A tool is needed to calculate this impact for each customer's order and also for overall orders of the customer over the time.

**Comment by Alireza89** [comment]
> According to american agricultural society in order to produce one kg meat, 34 kg co2 will be released in atmosphere .encouraging people to consume less meat is really important .one of the best way to inform people is telling them how much they will save if they do not use vegan,in fact many vegan do not know how much co2 will be saved when they are using plant based food.
> designing a software to calculate the amount of co2 which is saved by vegan when they are ordering a plant based food instead of meat based food and reporting them the overall saved co2 in the year.
> in addition they will notice that how much cholesterol and fat they will absorb if they use meat instead of vegan food.

let's focus on environmental impacts only and add health benefit to with the future version of the software

**Comment by alipartovi1990** [comment]
this sentence should be removed because it is related to the project goal. A tool is needed to calculate this impact for each customer's order and also for overall orders of the customer over the time.

**Comment by Alireza89** [comment]
> this sentence should be removed because it is related to the project goal. A tool is needed to calculate this impact for each customer's order and also for overall orders of the customer over the time.

Ok. Commit this change, then.

**Comment by Alireza89** [comment]
I'll close this issue.
final draft is:
Many vegans have chosen to avoid animal-based products because of its adverse environmental impacts. While they are aware of the positive environmental impacts of consuming plant-based foods, they might not know these impacts quantitatively and collectively. To solve this issue, we are planning to develop an ICDE software called VIE, acronym for “Vegan Impacts on the Environment”.
